In [5]:
import pandas as pd
import numpy as np
df=pd.read_csv("C:\\Users\\CVR\\Downloads\\traffic_accidents_dict new.csv")

In [2]:
cd

C:\Users\CVR

In [6]:
df

,accidents,traffic_fine_amount,traffic_density,traffic_lights,pavement_quality,urban_area,average_speed,rain_intensity,vehicle_count,time_of_day,Variable,Description
0,20,4.3709,2.3049,753.000,0.7700,1,321.5920,1.1944,290.8570,160.4320,accidents,"Number of recorded accidents, as a positive in..."
1,11,9.5564,3.2757,5.452,4.0540,1,478.6230,6.2960,931.8120,8.9108,traffic_fine_amount,"Traffic fine amount, expressed in thousands of..."
2,19,7.5879,2.0989,6.697,345.0000,0,364.4760,2.8584,830.0860,5.5727,traffic_density,"Traffic density index, scale from 0 (low) to 1..."
3,23,6.3879,4.9188,9.412,4.7290,0,20.9200,2.1065,813.1590,131.4520,traffic_lights,Proportion of traffic lights in the area (0 to...
4,23,2.4042,1.9610,7.393,1.7111,1,37.3780,1.7028,1.4663,6.9610,pavement_quality,"Pavement quality, scale from 0 (very poor) to ..."
...,...,...,...,...,...,...,...,...,...,...,...,...
8751,27,2.7683,6.9423,6.604,3.3575,1,302.0010,1.9822,258.9180,11.1542,0,0
8752,18,3.2629,1.7275,549.000,2.8478,1,6.2979,8.2730,296.4030,17.0410,0,0
8753,31,2.5621,8.5263,2.784,3.2826,1,479.9340,2.8239,458.2110,192.7690,0,0
8754,10,9.6205,1.4003,2.719,5.7760,1,280.7820,6.4030,147.6590,3.6364,0,0
8755,12,8.6916,4.1981,5.386,2.3801,0,234.6320,1.1225,483.9790,1.0790,0,0

In [7]:
df.head()

,accidents,traffic_fine_amount,traffic_density,traffic_lights,pavement_quality,urban_area,average_speed,rain_intensity,vehicle_count,time_of_day,Variable,Description
0,20,4.3709,2.3049,753.000,0.7700,1,321.592,1.1944,290.8570,160.4320,accidents,"Number of recorded accidents, as a positive in..."
1,11,9.5564,3.2757,5.452,4.0540,1,478.623,6.2960,931.8120,8.9108,traffic_fine_amount,"Traffic fine amount, expressed in thousands of..."
2,19,7.5879,2.0989,6.697,345.0000,0,364.476,2.8584,830.0860,5.5727,traffic_density,"Traffic density index, scale from 0 (low) to 1..."
3,23,6.3879,4.9188,9.412,4.7290,0,20.920,2.1065,813.1590,131.4520,traffic_lights,Proportion of traffic lights in the area (0 to...
4,23,2.4042,1.9610,7.393,1.7111,1,37.378,1.7028,1.4663,6.9610,pavement_quality,"Pavement quality, scale from 0 (very poor) to ..."

In [8]:
df.tail()

,accidents,traffic_fine_amount,traffic_density,traffic_lights,pavement_quality,urban_area,average_speed,rain_intensity,vehicle_count,time_of_day,Variable,Description
8751,27,2.7683,6.9423,6.604,3.3575,1,302.0010,1.9822,258.918,11.1542,0,0
8752,18,3.2629,1.7275,549.000,2.8478,1,6.2979,8.2730,296.403,17.0410,0,0
8753,31,2.5621,8.5263,2.784,3.2826,1,479.9340,2.8239,458.211,192.7690,0,0
8754,10,9.6205,1.4003,2.719,5.7760,1,280.7820,6.4030,147.659,3.6364,0,0
8755,12,8.6916,4.1981,5.386,2.3801,0,234.6320,1.1225,483.979,1.0790,0,0

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8756 entries, 0 to 8755
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   accidents            8756 non-null   int64
 1   traffic_fine_amount  8756 non-null   float64
 2   traffic_density      8756 non-null   float64
 3   traffic_lights       8756 non-null   float64
 4   pavement_quality     8756 non-null   float64
 5   urban_area           8756 non-null   int64
 6   average_speed        8756 non-null   float64
 7   rain_intensity       8756 non-null   float64
 8   vehicle_count        8756 non-null   float64
 9   time_of_day          8756 non-null   float64
 10  Variable             8756 non-null   object
 11  Description          8756 non-null   object
dtypes: float64(8), int64(2), object(2)
memory usage: 821.0+ KB

In [11]:
df.shape

(8756, 12)

In [12]:
df.describe()

,accidents,traffic_fine_amount,traffic_density,traffic_lights,pavement_quality,urban_area,average_speed,rain_intensity,vehicle_count,time_of_day
count,8756.000000,8756.000000,8756.000000,8756.000000,8756.000000,8756.000000,8756.000000,8756.000000,8756.000000,8756.000000
mean,20.625400,5.447824,14.252526,93.292068,22.442655,0.694381,214.642085,33.859295,453.234313,83.650263
std,5.228151,2.595654,75.965008,224.170457,112.193426,0.460695,168.707336,140.048354,313.882642,97.819456
min,5.000000,1.002000,0.240000,0.000000,0.000000,0.000000,0.970000,0.000000,1.026700,0.120000
25%,17.000000,3.195450,3.320775,3.775500,2.103350,0.000000,12.508500,1.668975,169.455750,6.514825
50%,21.000000,5.428500,5.563200,6.502500,3.276150,1.000000,223.125500,2.356450,453.982000,12.184300
75%,24.000000,7.675675,7.890175,9.226000,4.425700,1.000000,360.944750,3.704250,729.150250,174.777000
max,35.000000,9.997500,996.000000,999.000000,994.000000,1.000000,932.000000,999.000000,999.623000,999.000000

In [13]:
df.columns

Index(['accidents', 'traffic_fine_amount', 'traffic_density', 'traffic_lights',
       'pavement_quality', 'urban_area', 'average_speed', 'rain_intensity',
       'vehicle_count', 'time_of_day', 'Variable', 'Description'],
      dtype='object')

In [15]:
df.isnull().sum()

accidents              0
traffic_fine_amount    0
traffic_density        0
traffic_lights         0
pavement_quality       0
urban_area             0
average_speed          0
rain_intensity         0
vehicle_count          0
time_of_day            0
Variable               0
Description            0
dtype: int64

In [16]:
df.iloc[:,3]

0       753.000
1         5.452
2         6.697
3         9.412
4         7.393
         ...
8751      6.604
8752    549.000
8753      2.784
8754      2.719
8755      5.386
Name: traffic_lights, Length: 8756, dtype: float64

In [17]:
df['accidents'].unique

<bound method Series.unique of 0       20
1       11
2       19
3       23
4       23
        ..
8751    27
8752    18
8753    31
8754    10
8755    12
Name: accidents, Length: 8756, dtype: int64>

In [18]:
df.drop_duplicates()

,accidents,traffic_fine_amount,traffic_density,traffic_lights,pavement_quality,urban_area,average_speed,rain_intensity,vehicle_count,time_of_day,Variable,Description
0,20,4.3709,2.3049,753.000,0.7700,1,321.5920,1.1944,290.8570,160.4320,accidents,"Number of recorded accidents, as a positive in..."
1,11,9.5564,3.2757,5.452,4.0540,1,478.6230,6.2960,931.8120,8.9108,traffic_fine_amount,"Traffic fine amount, expressed in thousands of..."
2,19,7.5879,2.0989,6.697,345.0000,0,364.4760,2.8584,830.0860,5.5727,traffic_density,"Traffic density index, scale from 0 (low) to 1..."
3,23,6.3879,4.9188,9.412,4.7290,0,20.9200,2.1065,813.1590,131.4520,traffic_lights,Proportion of traffic lights in the area (0 to...
4,23,2.4042,1.9610,7.393,1.7111,1,37.3780,1.7028,1.4663,6.9610,pavement_quality,"Pavement quality, scale from 0 (very poor) to ..."
...,...,...,...,...,...,...,...,...,...,...,...,...
8751,27,2.7683,6.9423,6.604,3.3575,1,302.0010,1.9822,258.9180,11.1542,0,0
8752,18,3.2629,1.7275,549.000,2.8478,1,6.2979,8.2730,296.4030,17.0410,0,0
8753,31,2.5621,8.5263,2.784,3.2826,1,479.9340,2.8239,458.2110,192.7690,0,0
8754,10,9.6205,1.4003,2.719,5.7760,1,280.7820,6.4030,147.6590,3.6364,0,0
8755,12,8.6916,4.1981,5.386,2.3801,0,234.6320,1.1225,483.9790,1.0790,0,0

In [19]:
df.rename(columns={'traffic_fine_amount': 'traffic_amount'})

,accidents,traffic_amount,traffic_density,traffic_lights,pavement_quality,urban_area,average_speed,rain_intensity,vehicle_count,time_of_day,Variable,Description
0,20,4.3709,2.3049,753.000,0.7700,1,321.5920,1.1944,290.8570,160.4320,accidents,"Number of recorded accidents, as a positive in..."
1,11,9.5564,3.2757,5.452,4.0540,1,478.6230,6.2960,931.8120,8.9108,traffic_fine_amount,"Traffic fine amount, expressed in thousands of..."
2,19,7.5879,2.0989,6.697,345.0000,0,364.4760,2.8584,830.0860,5.5727,traffic_density,"Traffic density index, scale from 0 (low) to 1..."
3,23,6.3879,4.9188,9.412,4.7290,0,20.9200,2.1065,813.1590,131.4520,traffic_lights,Proportion of traffic lights in the area (0 to...
4,23,2.4042,1.9610,7.393,1.7111,1,37.3780,1.7028,1.4663,6.9610,pavement_quality,"Pavement quality, scale from 0 (very poor) to ..."
...,...,...,...,...,...,...,...,...,...,...,...,...
8751,27,2.7683,6.9423,6.604,3.3575,1,302.0010,1.9822,258.9180,11.1542,0,0
8752,18,3.2629,1.7275,549.000,2.8478,1,6.2979,8.2730,296.4030,17.0410,0,0
8753,31,2.5621,8.5263,2.784,3.2826,1,479.9340,2.8239,458.2110,192.7690,0,0
8754,10,9.6205,1.4003,2.719,5.7760,1,280.7820,6.4030,147.6590,3.6364,0,0
8755,12,8.6916,4.1981,5.386,2.3801,0,234.6320,1.1225,483.9790,1.0790,0,0

In [20]:
df['accidents'].mean()

20.625399725902238

In [21]:
df['accidents'].median()

21.0

In [22]:
df['accidents'].mode()

0    18
Name: accidents, dtype: int64

In [23]:
df['accidents'].std()

5.228150651505024

In [25]:
df.corr

<bound method DataFrame.corr of       accidents  traffic_fine_amount  traffic_density  traffic_lights  \
0            20               4.3709           2.3049         753.000
1            11               9.5564           3.2757           5.452
2            19               7.5879           2.0989           6.697
3            23               6.3879           4.9188           9.412
4            23               2.4042           1.9610           7.393
...         ...                  ...              ...             ...
8751         27               2.7683           6.9423           6.604
8752         18               3.2629           1.7275         549.000
8753         31               2.5621           8.5263           2.784
8754         10               9.6205           1.4003           2.719
8755         12               8.6916           4.1981           5.386

      pavement_quality  urban_area  average_speed  rain_intensity  \
0               0.7700           1       321.5920          1.1944
1               4.0540           1       478.6230          6.2960
2             345.0000           0       364.4760          2.8584
3               4.7290           0        20.9200          2.1065
4               1.7111           1        37.3780          1.7028
...                ...         ...            ...             ...
8751            3.3575           1       302.0010          1.9822
8752            2.8478           1         6.2979          8.2730
8753            3.2826           1       479.9340          2.8239
8754            5.7760           1       280.7820          6.4030
8755            2.3801           0       234.6320          1.1225

      vehicle_count  time_of_day             Variable  \
0          290.8570     160.4320            accidents
1          931.8120       8.9108  traffic_fine_amount
2          830.0860       5.5727      traffic_density
3          813.1590     131.4520       traffic_lights
4            1.4663       6.9610     pavement_quality
...             ...          ...                  ...
8751       258.9180      11.1542                    0
8752       296.4030      17.0410                    0
8753       458.2110     192.7690                    0
8754       147.6590       3.6364                    0
8755       483.9790       1.0790                    0

                                            Description
0     Number of recorded accidents, as a positive in...
1     Traffic fine amount, expressed in thousands of...
2     Traffic density index, scale from 0 (low) to 1...
3     Proportion of traffic lights in the area (0 to...
4     Pavement quality, scale from 0 (very poor) to ...
...                                                 ...
8751                                                  0
8752                                                  0
8753                                                  0
8754                                                  0
8755                                                  0

[8756 rows x 12 columns]>

In [26]:
df=pd.read_csv("C:\\Users\\CVR\\Downloads\\traffic_accidents_dict new.csv")
df.isnull().sum()

accidents              12
traffic_fine_amount     0
traffic_density         0
traffic_lights          0
pavement_quality        0
urban_area              0
average_speed           0
rain_intensity          0
vehicle_count           0
time_of_day             0
Variable                0
Description             0
dtype: int64

In [30]:
df.fillna('NULL')

,accidents,traffic_fine_amount,traffic_density,traffic_lights,pavement_quality,urban_area,average_speed,rain_intensity,vehicle_count,time_of_day,Variable,Description
0,20.0,4.3709,2.3049,753.000,0.7700,1,321.5920,1.1944,290.8570,160.4320,accidents,"Number of recorded accidents, as a positive in..."
1,11.0,9.5564,3.2757,5.452,4.0540,1,478.6230,6.2960,931.8120,8.9108,traffic_fine_amount,"Traffic fine amount, expressed in thousands of..."
2,19.0,7.5879,2.0989,6.697,345.0000,0,364.4760,2.8584,830.0860,5.5727,traffic_density,"Traffic density index, scale from 0 (low) to 1..."
3,23.0,6.3879,4.9188,9.412,4.7290,0,20.9200,2.1065,813.1590,131.4520,traffic_lights,Proportion of traffic lights in the area (0 to...
4,23.0,2.4042,1.9610,7.393,1.7111,1,37.3780,1.7028,1.4663,6.9610,pavement_quality,"Pavement quality, scale from 0 (very poor) to ..."
...,...,...,...,...,...,...,...,...,...,...,...,...
8751,27.0,2.7683,6.9423,6.604,3.3575,1,302.0010,1.9822,258.9180,11.1542,0,0
8752,18.0,3.2629,1.7275,549.000,2.8478,1,6.2979,8.2730,296.4030,17.0410,0,0
8753,31.0,2.5621,8.5263,2.784,3.2826,1,479.9340,2.8239,458.2110,192.7690,0,0
8754,10.0,9.6205,1.4003,2.719,5.7760,1,280.7820,6.4030,147.6590,3.6364,0,0
8755,12.0,8.6916,4.1981,5.386,2.3801,0,234.6320,1.1225,483.9790,1.0790,0,0

In [32]:
df.fillna(df['accidents'].mean())

,accidents,traffic_fine_amount,traffic_density,traffic_lights,pavement_quality,urban_area,average_speed,rain_intensity,vehicle_count,time_of_day,Variable,Description
0,20.0,4.3709,2.3049,753.000,0.7700,1,321.5920,1.1944,290.8570,160.4320,accidents,"Number of recorded accidents, as a positive in..."
1,11.0,9.5564,3.2757,5.452,4.0540,1,478.6230,6.2960,931.8120,8.9108,traffic_fine_amount,"Traffic fine amount, expressed in thousands of..."
2,19.0,7.5879,2.0989,6.697,345.0000,0,364.4760,2.8584,830.0860,5.5727,traffic_density,"Traffic density index, scale from 0 (low) to 1..."
3,23.0,6.3879,4.9188,9.412,4.7290,0,20.9200,2.1065,813.1590,131.4520,traffic_lights,Proportion of traffic lights in the area (0 to...
4,23.0,2.4042,1.9610,7.393,1.7111,1,37.3780,1.7028,1.4663,6.9610,pavement_quality,"Pavement quality, scale from 0 (very poor) to ..."
...,...,...,...,...,...,...,...,...,...,...,...,...
8751,27.0,2.7683,6.9423,6.604,3.3575,1,302.0010,1.9822,258.9180,11.1542,0,0
8752,18.0,3.2629,1.7275,549.000,2.8478,1,6.2979,8.2730,296.4030,17.0410,0,0
8753,31.0,2.5621,8.5263,2.784,3.2826,1,479.9340,2.8239,458.2110,192.7690,0,0
8754,10.0,9.6205,1.4003,2.719,5.7760,1,280.7820,6.4030,147.6590,3.6364,0,0
8755,12.0,8.6916,4.1981,5.386,2.3801,0,234.6320,1.1225,483.9790,1.0790,0,0